export const PEGAWAI_TAMBAH_REQUEST = 'PEGAWAI_TAMBAH_REQUEST';
export const PEGAWAI_TAMBAH_SUCCESS = 'PEGAWAI_TAMBAH_SUCCESS';
export const PEGAWAI_TAMBAH_FAIL = 'PEGAWAI_TAMBAH_FAIL';
export const PEGAWAI_TAMBAH_RESET = 'PEGAWAI_TAMBAH_RESET';

export const PEGAWAI_LIST_REQUEST = 'PEGAWAI_LIST_REQUEST';
export const PEGAWAI_LIST_SUCCESS = 'PEGAWAI_LIST_SUCCESS';
export const PEGAWAI_LIST_FAIL = 'PEGAWAI_LIST_FAIL';
export const PEGAWAI_LIST_RESET = 'PEGAWAI_LIST_RESET';

export const PEGAWAI_UPDATE_REQUEST = 'PEGAWAI_UPDATE_REQUEST';
export const PEGAWAI_UPDATE_SUCCESS = 'PEGAWAI_UPDATE_SUCCESS';
export const PEGAWAI_UPDATE_FAIL = 'PEGAWAI_UPDATE_FAIL';
export const PEGAWAI_UPDATE_RESET = 'PEGAWAI_UPDATE_RESET';

export const PEGAWAI_DELETE_REQUEST = 'PEGAWAI_DELETE_REQUEST';
export const PEGAWAI_DELETE_SUCCESS = 'PEGAWAI_DELETE_SUCCESS';
export const PEGAWAI_DELETE_FAIL = 'PEGAWAI_DELETE_FAIL';
export const PEGAWAI_DELETE_RESET = 'PEGAWAI_DELETE_RESET';
